
#Range: min = 0, max = 2147483647
["Basic Enregy Cell"]
	transfer = "2000"
	capacity = "250000"

["Hardened Enregy Cell"]
	transfer = "4000"
	capacity = "1000000"

["Blazing Enregy Cell"]
	transfer = "8000"
	capacity = "4000000"

["Niotic Enregy Cell"]
	transfer = "16000"
	capacity = "8000000"

["Spirited Enregy Cell"]
	transfer = "32000"
	capacity = "16000000"

