
#Range: min = 0, max = 2147483647
["Player Transmitter"]
	transfer = "1000"
	capacity = "100000"

["Dimensional Player Transmitter"]
	transfer = "2500"
	capacity = "250000"

["Energy Discharger"]
	transfer = "100000"
	capacity = "1000000"

["Energy Hopper"]
	transfer = "10000"
	capacity = "1000000"

