
#General mod settings
[general]
	#Defines how far away you can build
	#Range: 1.0 ~ 48.0
	MaxBuildDistance = 32.0
	#Whether the Building / CopyPaste Gadget can overwrite blocks like water, lava, grass, etc (like a player can).
	#False will only allow it to overwrite air blocks.
	"Allow non-Air-Block-Overwrite" = true

#Charging station settings
[charging_station]
	#Define the maximum energy stored in the Charging Station.
	#Range: > 1
	"Energy capacity" = 1000000
	#Define the speed factor, by which the fuel is going to be consumed.
	#Range: 1.0E-8 ~ 1.7976931348623157E308
	"Fuel Usage" = 50.0
	#Define the amount of energy produced per fuel tick.
	#Range: > 0
	"Energy Production" = 750
	#Define how much the charging station attempts to charge per tick
	#Range: > 0
	"Charge Energy" = 2500
	#Define how much Energy can be accepted by the Charging Station per tick. Note that burning fuel counts towards this cap.
	#Range: > 0
	"Max Energy Recieved" = 750
	#Define how much Energy can at most be extracted from the Charging Station per tick. Charging Items does notcount towards this cap!
	#Range: > 0
	"Max Energy Extracted" = 0

#Configure the Gadgets
[Gadgets]
	#The max range of the Gadgets
	#Range: 1 ~ 32
	"Maximum allowed Range" = 15

	#Energy Cost & Durability of the Building Gadget
	[Gadgets."Building Gadget"]
		#The max energy of the Gadget
		#Range: > 1
		"Maximum Energy" = 500000
		#The Gadget's Energy cost per Operation
		#Range: > 0
		"Energy Cost" = 50

	#Energy Cost & Durability of the Exchanging Gadget
	[Gadgets."Exchanging Gadget"]
		#The max energy of the Gadget
		#Range: > 1
		"Maximum Energy" = 500000
		#The Gadget's Energy cost per Operation
		#Range: > 0
		"Energy Cost" = 100

	#Energy Cost, Durability & Maximum Energy of the Destruction Gadget
	[Gadgets."Destruction Gadget"]
		#The max energy of the Gadget
		#Range: > 1
		"Maximum Energy" = 1000000
		#The Gadget's Energy cost per Operation
		#Range: > 0
		"Energy Cost" = 200
		#The cost in energy/durability will increase by this amount when not in fuzzy mode
		#Range: 0.0 ~ 1.7976931348623157E308
		"Non-Fuzzy Mode Multiplier" = 2.0
		#If enabled, the Destruction Gadget can be taken out of fuzzy mode, allowing only instances of the block clicked to be removed (at a higher cost)
		"Non-Fuzzy Mode Enabled" = false

	#Energy Cost & Durability of the Copy-Paste Gadget
	[Gadgets."Copy-Paste Gadget"]
		#The max energy of the Gadget
		#Range: > 1
		"Maximum Energy" = 500000
		#The Gadget's Energy cost per Operation
		#Range: > 0
		"Energy Cost" = 50

#Configure the Paste Containers
["Paste Containers"]
	#The maximum capacity of a tier 1 (iron) Construction Paste Container
	#Range: > 1
	"T1 Container Capacity" = 512
	#The maximum capacity of a tier 2 (iron) Construction Paste Container
	#Range: > 1
	"T2 Container Capacity" = 2048
	#The maximum capacity of a tier 3 (iron) Construction Paste Container
	#Range: > 1
	"T3 Container Capacity" = 8192

#Configure your Blacklist-Settings here
["Blacklist Settings"]
	#All Blocks added to this will be treated similar to TileEntities. Not at all.
	#Notice that you can use Regular Expressions as defined by Java Patterns to express more complex name combinations.
	#Use for example "awfulmod:.*" to blacklist all awfulmod Blocks.
	"Blacklisted Blocks" = ["minecraft:.*_door.*", "minecraft:piston_head"]
	#Allows you to define a whitelist, allowing Patterns to be defined in the same way as the blacklist.
	"Whitelisted Blocks" = [".*"]

