
#Loot configuration
[loot]
	#Is the mod's vanilla mob loot enabled?
	mob_loot = true
	#Is the mod's vanilla structure loot enabled?
	struct_loot = true

	#Structure loot settings
	[loot.structure]
		#Chance of a BountifulBaubles item spawning in a nether fortress chest
		#(excluding recall/wormhole potions). 0 to disable.
		#Range: 0.0 ~ 1.0
		nether_base = 0.2
		#Chance of recall or wormhole potions spawning in a dungeon chest. 0 to disable.
		#Range: 0.0 ~ 1.0
		dungeon_potion = 0.75
		#Chance of a BountifulBaubles item spawning in a dungeon chest
		#(excluding recall/wormhole potions). 0 to disable.
		#Range: 0.0 ~ 1.0
		dungeon_base = 0.35

#Item configuration
[items]

	#Ender Dragon Scale settings
	[items.ender_dragon_scale]
		#Does the ender dragon drop scales?
		dragon_scale_drop_enabled = true

	#Broken Heart settings
	[items.broken_heart]
		#Amount of max HP regained each sleep, in half hearts.
		#Does nothing if max HP regeneration is not enabled
		#Range: 0.0 ~ 1.7976931348623157E308
		regen_amount = 4.0
		#Can max HP lost to the broken heart be regained?
		#(recommended false on hardcore mode, true otherwise)
		regen = true

	#Magic Mirror settings
	[items.magic_mirror]
		#Can magic/wormhole mirrors and recall potions recall interdimensionally?
		magic_mirror_interdimensional = false

