
#Configuration related to Immersive Engineering wires
[wires]
	#If this is enabled, placing a block in a wire will break it (drop the wire coil)
	blocksBreakWires = true
	#The percentage of power lost every 16 blocks of distance for the wire tiers (copper, electrum, HV, Structural Rope, Cable & Redstone(no transfer) )
	wireLossRatio = [0.05, 0.025, 0.025, 1.0, 1.0, 1.0]
	#The transfer rates in Flux/t for the wire tiers (copper, electrum, HV, Structural Rope, Cable & Redstone (no transfer) )
	wireTransferRate = [2048, 8192, 32768, 0, 0, 0]
	#"The maximum length wire can have. Copper and Electrum should be similar, Steel is meant for long range transport, Structural Rope & Cables are purely decorational"
	wireLength = [16, 16, 32, 32, 32, 32]
	#Enable detailed logging for the wire network. This can be useful for developers to track down issues related to wires.
	enableWireLogger = false
	#The RGB colourate of the wires.
	wireColouration = [11758655, 15573061, 7303023, 9862765, 7303023, 16723759, 16445918, 10323322]
	#Attempts to make the internal data structures used for wires consistent with the connectors in the world.Use with care and backups and only when suspecting corrupted data.
	#This option will check and load all connection endpoints and may slow down the world loading process.
	sanitizeConnections = false
	#If this is enabled, wires connected to power sources will cause damage to entities touching them
	#This shouldn't cause significant lag but possibly will. If it does, please report it at https://github.com/BluSunrize/ImmersiveEngineering/issues unless there is a report of it already.
	enableWireDamage = true

[General]
	#The weight that hempseeds have when breaking tall grass. 5 by default, set to 0 to disable drops
	#Range: > 0
	hempSeedWeight = 5
	#A config setting to enable debug features. These features may vary between releases, may cause crashes, and are unsupported. Do not enable unless asked to by a developer of IE.
	enableDebug = false
	#Set this to false to hide the update news in the manual
	showUpdateNews = true
	#Set this to false to disable the super awesome looking nixie tube front for the voltmeter and other things
	nixietubeFont = true
	#A list of preferred Mod IDs that results of IE processes should stem from, aka which mod you want the copper to come from.
	#This affects the ores dug by the excavator, as well as those crushing recipes that don't have associated IE items. This list is in oreder of priority.
	preferredOres = ["minecraft", "kubejs", "silents_mechanisms", "immersiveengineering", "bluepower", "botania", "mysticalworld", "tmechworks", "industrialforegoing"]
	#Controls if item tooltips should contain the tags names of items. These tooltips are only visible in advanced tooltip mode (F3+H)
	tagTooltips = false
	#Set this to true if you suffer from bad eyesight. The Engineer's manual will be switched to a bold and darker text to improve readability.
	#Note that this may lead to a break of formatting and have text go off the page in some instances. This is unavoidable.
	badEyesight = false
	#Set this to false to remove IE villagers from the game
	enableVillagers = true
	#Set to false to disable the stencil buffer. This may be necessary on older GPUs.
	stencilBufferEnabled = true
	#Set this to false to stop the IE villager house from spawning
	villagerHouse = true
	#Set this to false to disable the manual's forced change of GUI scale
	adjustManualScale = false
	#Increase the distance at which certain TileEntities (specifically windmills) are still visible. This is a modifier, so set it to 1 for default render distance, to 2 for doubled distance and so on.
	#Range: 0.0 ~ 1.7976931348623157E308
	increasedTileRenderdistance = 1.5
	#Disables most lighting code for certain models that are rendered dynamically (TESR). May improve FPS.
	#Affects turrets and garden cloches
	disableFancyTESR = false
	#Allows revolvers and other IE items to look properly held in 3rd person. This uses a coremod. Can be disabled in case of conflicts with other animation mods.
	fancyItemHolding = true
	#Show the text overlay for various blocks, such as the configuration of capacitors or pumps
	showTextOverlay = true

[machines]
	#Set this to false to disable the mob-spawn prevention of the Floodlight
	floodlight_spawnPrevent = true
	#The chance that a given chunk will contain a mineral vein.
	#Range: 0.001 ~ 1.0
	excavator_chance = 0.2
	#A base-modifier for all fluid fertilizers in the cloche
	#Range: 0.001 ~ 1000.0
	garden_cloche_fluid_fertilizer_mod = 1.0
	#The Flux the Assembler will consume to craft an item from a recipe
	#Range: > 1
	assembler_consumption = 80
	#A modifier to apply to the time of every fermenter recipe
	#Range: 0.001 ~ 1000.0
	fermenter_timeModifier = 1.0
	#A modifier to apply to the energy costs of every refinery recipe
	#Range: 0.001 ~ 1000.0
	refinery_energyModifier = 1.0
	#A modifier to apply to the time of every crusher recipe
	#Range: 0.001 ~ 1000.0
	crusher_timeModifier = 1.0
	#How much Flux the powered lantern draws per tick
	#Range: > 1
	lantern_energyDraw = 1
	#The maximum amount of yield one can get out of a chunk with the excavator. Set a number smaller than zero to make it infinite
	#Range: > -1
	excavator_depletion = 38400
	#A modifier to apply to the time of every metal press recipe
	#Range: 0.001 ~ 1000.0
	metal_press_timeModifier = 1.0
	#The Flux per tick the gun turret consumes to shoot
	#Range: > 1
	turret_gun_consumption = 32
	#A modifier to apply to the energy costs of every mixer recipe
	#Range: 0.001 ~ 1000.0
	mixer_energyModifier = 1.0
	#List of dimensions that can't contain minerals. Default: The End.
	excavator_dimBlacklist = ["minecraft:the_end"]
	#The Flux per tick the cloche consumes to grow plants
	#Range: > 1
	garden_cloche_consumption = 8
	#The Flux per tick consumed to double the speed of the furnace. Only happens if furnace is at maximum heat.
	#Range: > 1
	heater_speedupConsumption = 24
	#A modifier to apply to the time of every refinery recipe
	#Range: 0.001 ~ 1000.0
	refinery_timeModifier = 1.0
	#How much Flux the floodlight can hold (must be at least 10x the power draw)
	#Range: > 1
	floodlight_max_storage = 80
	#The speed of the Excavator. Basically translates to how many degrees per tick it will turn.
	#Range: 0.001 ~ 1000.0
	excavator_speed = 1.0
	#The base Flux that is output by the dynamo. This will be modified by the rotation modifier of the attached water- or windmill
	#Range: 0.0 ~ 2.147483647E9
	dynamo_output = 3.0
	#The Flux the Fluid Pump will consume pressurize and accelerate fluids, increasing the transferrate
	#Range: > 1
	pump_consumption_accelerate = 5
	#How much Flux the powered lantern can hold (should be greater than the power draw)
	#Range: > 1
	lantern_max_storage = 10
	#The amount of ticks one dose of fertilizer lasts in the cloche
	#Range: > 1
	garden_cloche_fertilizer = 6000
	#A modifier to apply to the energy costs of every fermenter recipe
	#Range: 0.001 ~ 1000.0
	fermenter_energyModifier = 1.0
	#The Flux per tick the Blast Furnace Preheater will consume to speed up the Blast Furnace
	#Range: > 1
	preheater_consumption = 32
	#The Flux per tick consumed by the Core Sample Drill
	#Range: > 1
	coredrill_consumption = 40
	#A modifier to apply to the energy costs of every metal press recipe
	#Range: 0.001 ~ 1000.0
	metal_press_energyModifier = 1.0
	#A modifier to apply to the energy costs of every crusher recipe
	#Range: 0.001 ~ 1000.0
	crusher_energyModifier = 1.0
	#The Flux per tick the Tesla Coil will consume, simply by being active
	#Range: > 1
	teslacoil_consumption = 256
	#The chance that the Excavator will not dig up an ore with the currently downward-facing bucket.
	#Range: 0.0 ~ 1.0
	excavator_fail_chance = 0.05
	#The Flux per tick consumed to add one heat to a furnace. Creates up to 4 heat in the startup time and then 1 heat per tick to keep it running
	#Range: > 1
	heater_consumption = 8
	#The Flux per tick the Excavator will consume to dig
	#Range: > 1
	excavator_consumption = 4096
	#The Flux per tick that the Diesel Generator will output. The burn time of the fuel determines the total output
	#Range: > 0
	dieselGen_output = 4096
	#The amount of Flux the Tesla Coil will consume when shocking an entity
	#Range: > 1
	teslacoil_consumption_active = 512
	#The Flux per tick the chemthrower turret consumes to shoot
	#Range: > 1
	turret_chem_consumption = 32
	#Output modifier for the energy created by the Thermoelectric Generator
	#Range: 0.0 ~ 2.147483647E9
	thermoelectric_output = 1.0
	#A modifier to apply to the time of every bottling machine recipe
	#Range: 0.001 ~ 1000.0
	bottling_machine_timeModifier = 1.0
	#Set this to false to disable the fluid pump being able to draw infinite water from sources
	pump_infiniteWater = true
	#A modifier to apply to the time of every squeezer recipe
	#Range: 0.001 ~ 1000.0
	squeezer_timeModifier = 1.0
	#A modifier to apply to the energy costs of every arc furnace recipe
	#Range: 0.001 ~ 1000.0
	arc_furnace_energyModifier = 1.0
	#The length in ticks it takes for the Core Sample Drill to figure out which mineral is found in a chunk
	#Range: > 1
	coredrill_time = 200
	#A modifier to apply to the cloches total growing speed
	#Range: 0.001 ~ 1000.0
	garden_cloche_growth_modifier = 1.0
	#A base-modifier for all solid fertilizers in the cloche
	#Range: 0.001 ~ 1000.0
	garden_cloche_solid_fertilizer_mod = 1.0
	#The maximum amount of damage Graphite Electrodes can take. While the furnace is working, electrodes sustain 1 damage per tick, so this is effectively the lifetime in ticks. The default value of 96000 makes them last for 8 consecutive ingame days
	#Range: > 1
	arcfurnace_electrodeDamage = 96000
	#A modifier to apply to the energy costs of every auto workbench recipe
	#Range: 0.001 ~ 1000.0
	auto_workbench_energyModifier = 1.0
	#The Flux per tick the Charging Station can insert into an item
	#Range: > 1
	charger_consumption = 256
	#A modifier to apply to the time of every mixer recipe
	#Range: 0.001 ~ 1000.0
	mixer_timeModifier = 1.0
	#The amount of fluid the cloche uses per dose of fertilizer
	#Range: > 1
	garden_cloche_fluid = 250
	#Set this to false to disable the ridiculous amounts of particles the Excavator spawns
	excavator_particles = true
	#In- and output rates of LV,MV and HV Wire Conenctors. This is independant of the transferrate of the wires.
	wireConnectorInput = [256, 1024, 4096]
	#The Flux per tick any turret consumes to monitor the area
	#Range: > 1
	turret_consumption = 64
	#How much Flux the floodlight draws per tick
	#Range: > 1
	floodlight_energyDraw = 5
	#A modifier to apply to the time of every arc furnace recipe
	#Range: 0.001 ~ 1000.0
	arc_furnace_timeModifier = 1.0
	#Set this to false to disable the mob-spawn prevention of the Powered Lantern
	lantern_SpawnPrevent = true
	#Set this to false to disable the Arc Furnace's recycling of armors and tools
	arcfurnace_recycle = true
	#The amount of damage the Tesla Coil will do when shocking an entity
	#Range: 0.0 ~ 2.147483647E9
	teslacoil_damage = 6.0
	#A modifier to apply to the energy costs of every squeezer recipe
	#Range: 0.001 ~ 1000.0
	squeezer_energyModifier = 1.0
	#Set this to true to make the blueprint for graphite electrodes craftable in addition to villager/dungeon loot
	arcfurnace_electrodeCrafting = false
	#If this is set to true (default) the pump will replace fluids it picks up with cobblestone in order to reduce lag caused by flowing fluids.
	pump_placeCobble = true
	#A modifier to apply to the time of every auto workbench recipe
	#Range: 0.001 ~ 1000.0
	auto_workbench_timeModifier = 1.0
	#The Flux that will be output by the lightning rod when it is struck
	#Range: > 0
	lightning_output = 16000000
	#The Flux the Fluid Pump will consume to pick up a fluid block in the world
	#Range: > 1
	pump_consumption = 250
	#A modifier to apply to the energy costs of every bottling machine recipe
	#Range: 0.001 ~ 1000.0
	bottling_machine_energyModifier = 1.0

	[machines.capacitors]

		#Configuration for the medium voltage capacitor
		[machines.capacitors.mv]
			#Maximum energy output (Flux/tick)
			#Range: > 1
			capacitorMV_output = 1024
			#Maximum energy stored (Flux)
			#Range: > 1
			capacitorMV_storage = 1000000
			#Maximum energy input (Flux/tick)
			#Range: > 1
			capacitorMV_input = 1024

		#Configuration for the low voltage capacitor
		[machines.capacitors.lv]
			#Maximum energy stored (Flux)
			#Range: > 1
			capacitorLV_storage = 100000
			#Maximum energy input (Flux/tick)
			#Range: > 1
			capacitorLV_input = 256
			#Maximum energy output (Flux/tick)
			#Range: > 1
			capacitorLV_output = 256

		#Configuration for the high voltage capacitor
		[machines.capacitors.hv]
			#Maximum energy output (Flux/tick)
			#Range: > 1
			capacitorHV_output = 4096
			#Maximum energy input (Flux/tick)
			#Range: > 1
			capacitorHV_input = 4096
			#Maximum energy stored (Flux)
			#Range: > 1
			capacitorHV_storage = 4000000

[ores]
	#A blacklist of dimensions in which IE ores won't spawn. By default this is Nether and End
	dimension_blocklist = ["minecraft:the_nether", "minecraft:the_end"]
	#Set this to false to disable the logging of the chunks that were flagged for retrogen.
	retrogen_log_flagChunk = true
	#The retrogeneration key. Basically IE checks if this key is saved in the chunks data. If it isn't, it will perform retrogen on all ores marked for retrogen.
	#Change this in combination with the retrogen booleans to regen only some of the ores.
	retrogen_key = "DEFAULT"
	#Set this to false to disable the logging of the chunks that are still left to retrogen.
	retrogen_log_remaining = true

	#Ore generation config - nickel
	[ores.nickel]
		#The maximum Y coordinate this ore can spawn at
		#Range: > -2147483648
		max_y = 24
		#The average number of veins per chunk
		#Range: > 0
		avg_veins_per_chunk = 2
		#The maximum size of a vein. Set to 0 to disable generation
		#Range: > 0
		vein_size = 0
		#Set this to true to allow retro-generation of nickel Ore.
		retrogen_enable = false
		#The minimum Y coordinate this ore can spawn at
		#Range: > -2147483648
		min_y = 8

	#Ore generation config - copper
	[ores.copper]
		#The maximum Y coordinate this ore can spawn at
		#Range: > -2147483648
		max_y = 72
		#The average number of veins per chunk
		#Range: > 0
		avg_veins_per_chunk = 8
		#The maximum size of a vein. Set to 0 to disable generation
		#Range: > 0
		vein_size = 0
		#Set this to true to allow retro-generation of copper Ore.
		retrogen_enable = false
		#The minimum Y coordinate this ore can spawn at
		#Range: > -2147483648
		min_y = 40

	#Ore generation config - bauxite
	[ores.bauxite]
		#The maximum Y coordinate this ore can spawn at
		#Range: > -2147483648
		max_y = 85
		#The average number of veins per chunk
		#Range: > 0
		avg_veins_per_chunk = 8
		#The maximum size of a vein. Set to 0 to disable generation
		#Range: > 0
		vein_size = 0
		#Set this to true to allow retro-generation of bauxite Ore.
		retrogen_enable = false
		#The minimum Y coordinate this ore can spawn at
		#Range: > -2147483648
		min_y = 40

	#Ore generation config - silver
	[ores.silver]
		#The maximum Y coordinate this ore can spawn at
		#Range: > -2147483648
		max_y = 40
		#The average number of veins per chunk
		#Range: > 0
		avg_veins_per_chunk = 4
		#The maximum size of a vein. Set to 0 to disable generation
		#Range: > 0
		vein_size = 0
		#Set this to true to allow retro-generation of silver Ore.
		retrogen_enable = false
		#The minimum Y coordinate this ore can spawn at
		#Range: > -2147483648
		min_y = 8

	#Ore generation config - uranium
	[ores.uranium]
		#The maximum Y coordinate this ore can spawn at
		#Range: > -2147483648
		max_y = 24
		#The average number of veins per chunk
		#Range: > 0
		avg_veins_per_chunk = 2
		#The maximum size of a vein. Set to 0 to disable generation
		#Range: > 0
		vein_size = 0
		#Set this to true to allow retro-generation of uranium Ore.
		retrogen_enable = false
		#The minimum Y coordinate this ore can spawn at
		#Range: > -2147483648
		min_y = 8

	#Ore generation config - lead
	[ores.lead]
		#The maximum Y coordinate this ore can spawn at
		#Range: > -2147483648
		max_y = 36
		#The average number of veins per chunk
		#Range: > 0
		avg_veins_per_chunk = 4
		#The maximum size of a vein. Set to 0 to disable generation
		#Range: > 0
		vein_size = 0
		#Set this to true to allow retro-generation of lead Ore.
		retrogen_enable = false
		#The minimum Y coordinate this ore can spawn at
		#Range: > -2147483648
		min_y = 8

[tools]
	#The amount of base damage a armor piercing Cartridge inflicts
	#Range: 0.0 ~ 1.7976931348623157E308
	bulletDamage_ap = 10.0
	#The amount of base damage a wolfpack cartridge inflicts
	#Range: 0.0 ~ 1.7976931348623157E308
	bulletDamage_wolfpack = 6.0
	#The base amount of Flux consumed per shot by the Railgun
	#Range: > 1
	railgun_consumption = 800
	#The amount of base damage a dragon breath cartridge inflicts
	#Range: 0.0 ~ 1.7976931348623157E308
	bulletDamage_dragon = 3.0
	#Set this to false to disable the use of Sneak+Scroll to switch Chemthrower tanks.
	chemthrower_scroll = true
	#The amount of base damage the sub-projectiles of a  wolfpack cartridge inflicts
	#Range: 0.0 ~ 1.7976931348623157E308
	bulletDamage_wolfpack_part = 4.0
	#A list of sounds that should not be muffled by the Ear Defenders. Adding to this list requires knowledge of the correct sound resource names.
	earDefenders_SoundBlacklist = []
	#Set this to true to completely disable the ore-crushing recipes with the Engineers Hammer
	disable_hammer_crushing = false
	#The amount of base damage a Casull Cartridge inflicts
	#Range: 0.0 ~ 1.7976931348623157E308
	bulletDamage_casull = 10.0
	#The maximum durability of the Wirecutter. Used up when cutting plates into wire.
	#Range: > 1
	cutter_durability = 250
	#The amount of base damage a phial cartridge inflicts
	#Range: 0.0 ~ 1.7976931348623157E308
	bulletDamage_phial = 1.0
	#A whitelist of wire-related allowed in the toolbox, formatting: [mod id]:[item name]
	toolbox_wiring = []
	#A blacklist of armor pieces to allow attaching the capacitor backpack, formatting: [mod id]:[item name]. Whitelist has priority over this
	powerpack_blacklist = ["embers:ashen_cloak_chest", "ic2:batpack", "ic2:cf_pack", "ic2:energy_pack", "ic2:jetpack", "ic2:jetpack_electric", "ic2:lappack"]
	#A whitelist of armor pieces to allow attaching the capacitor backpack, formatting: [mod id]:[item name]
	powerpack_whitelist = []
	#A whitelist of foods allowed in the toolbox, formatting: [mod id]:[item name]
	toolbox_foods = []
	#A whitelist of tools allowed in the toolbox, formatting: [mod id]:[item name]
	toolbox_tools = []
	#The mb of fluid the Chemical Thrower will consume per tick of usage
	#Range: > 1
	chemthrower_consumption = 10
	#The amount of base damage a single part of buckshot inflicts
	#Range: 0.0 ~ 1.7976931348623157E308
	bulletDamage_buck = 2.0
	#The amount of damage a silver bullet inflicts
	#Range: 0.0 ~ 1.7976931348623157E308
	bulletDamage_silver = 10.0
	#The amount of base damage a homing cartridge inflicts
	#Range: 0.0 ~ 1.7976931348623157E308
	bulletDamage_homing = 10.0
	#The maximum durability of the Engineer's Hammer. Used up when hammering ingots into plates.
	#Range: > 1
	hammer_durability = 100
	#A modifier for the damage of all projectiles fired by the Railgun
	#Range: 0.0 ~ 1.7976931348623157E308
	railgun_damage_modifier = 1.0

