
#Select A GUI Style
[gui_style]
	#Allowed Values: DEFAULT, VANILLA
	"Embroidery Thread" = "DEFAULT"
	#Allowed Values: DEFAULT, VANILLA
	"Bed/Ladder Builder" = "DEFAULT"
	#Allowed Values: DEFAULT, VANILLA
	"Blanket Loom" = "DEFAULT"

