
[General]
	#The amount of blocks that are instantly converted to a nether block around a portal when it is detected. If there are existing nether blocks within the radius, their count is substracted from this number.
	#Range: 0 ~ 1000
	instantConvertAmount = 50
	#The amount of prevent-spread-blocks (defined) needed within the radius of the nether portal to prevent spread.
	preventSpreadBlockAmountNeeded = 2
	#The chance a soul sand block with an airblock above has netherwart growing out of it.
	#Range: 0.0 ~ 1.0
	surfaceSoulSandHasNetherwartChance = 0.25
	#When enabled, blocks the spread effect when there are n (defined) prevent-spread-blocks (defined) within the radius.
	preventSpreadWithBlock = true
	#The radius around the portal to which the nether blocks can spread.
	#Range: 1 ~ 100
	portalSpreadRadius = 15
	#The delay in ms in between the spread around the nether portal.
	#Range: 20 ~ 360000
	spreadDelay = 2500
	#The block which prevents the nether portal from spreading. By default a coal block (minecraft:coal_block is the namespace ID)
	preventSpreadBlockString = "minecraft:coal_block"

