
#Settings related to the Java architecture.
[jvm-architecture]
	#Should people using 32 bit Java be warned and asked to use 64 bit Java instead?
	warn32Bit = true

#Settings related to Java's memory management.
[memory]
	#Should users with low RAM be warned?
	warnLowMemory = true
	#The amount of recommended ram to play the pack. This is in megabytes.
	recommendedRam = 4096

#Settings related to checking for a very specific Minecraft version.
[java-version]
	#What is the minimum version of Java to look for?
	minVersion = "1.8.0_162"
	#Whether or not the Java version should be checked.
	enabled = true

